### ISSUE TITLE
Your plugin does not locate the right file

### ISSUE THREAD

**Issue by talley** [tunnelvisionlabs/FindInSolutionExplorer#18]
Your plugin does not locate the right file

**Comment by sharwell** [comment]
This plugin has been effectively obsolete since Visual Studio 2012, but I kept it published by request of some users who were used to it. There is a button at the top of Solution Explorer which will locate the correct file.

More information is available in the readme: https://github.com/tunnelvisionlabs/FindInSolutionExplorer#find-in-solution-explorer-extension-for-visual-studio-2012
