### ISSUE TITLE
Vs 15 Support

### ISSUE THREAD

**Issue by valeriob** [tunnelvisionlabs/FindInSolutionExplorer#2]
It's mandatory to begin using vs 15 😄

**Comment by sharwell** [comment]
@valeriob Visual Studio 2012+ has this feature built-in. I've noticed this hasn't stopped people from continuing to request it. Is there a particular reason why you're a fan of this extension over the built-in functionality?

**Comment by valeriob** [comment]
I guess nobody like me knew it :D The name "Sync with Active Document" is kind of misterious...
But most of all, the visual studio button is in the wrong place, is far more comfortable if it is in the tab context menu.

**Comment by sharwell** [comment]
@valeriob Thanks for the update. I'll see about getting this updated in the next couple of weeks.

**Comment by valeriob** [comment]
Thank you !

**Comment by sharwell** [comment]
@valeriob I enabled AppVeyor on this project, so if you visit the pull request where this issue is fixed (#6) and navigate to the AppVeyor build results, you'll find an artifacts tab. On that page you'll find a build of the VSIX which should support Visual Studio 2017.

:memo: After I verify on one of my machines that the build truly does support Visual Studio 2017, I'll merge the request and get an update uploaded to the marketplace.
